---
LLM: llama2-70b
dataset: MedMCQA
prompt_file: "prompts/MedMCQA.json"
max_new_tokens: 1
if_RA: True
if_MI_RA: False
if_train: False
retrieval_raw_data_dir: "datasets/USMLE/textbooks/en"
retrieval_processed_file_dir: "datasets/USMLE/process_retrieval_corpus/"
test_code_flag: True
train_eval: 1
