---
LLM: llama2-7b
dataset: USMLE
prompt_file: "prompts/USMLE.json"
max_new_tokens: 2
if_RA: True
retrieval_raw_data_dir: "datasets/USMLE/textbooks/en"
retrieval_processed_file_dir: "datasets/USMLE/process_retrieval_corpus/"
demonstration: true
demons_cnt: 1

